//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mail.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mail.lang.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string adduser_advanced {
            get {
                return ResourceManager.GetString("adduser_advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check &amp; Add.
        /// </summary>
        public static string adduser_checkadd {
            get {
                return ResourceManager.GetString("adduser_checkadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string adduser_email {
            get {
                return ResourceManager.GetString("adduser_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption.
        /// </summary>
        public static string adduser_encryption {
            get {
                return ResourceManager.GetString("adduser_encryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string adduser_encryption_auto {
            get {
                return ResourceManager.GetString("adduser_encryption_auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string adduser_encryption_none {
            get {
                return ResourceManager.GetString("adduser_encryption_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn`t connect to imap. .
        /// </summary>
        public static string adduser_imaperror {
            get {
                return ResourceManager.GetString("adduser_imaperror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsUseAuth.
        /// </summary>
        public static string adduser_isuseauth {
            get {
                return ResourceManager.GetString("adduser_isuseauth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something is not filled in.
        /// </summary>
        public static string adduser_notfilled {
            get {
                return ResourceManager.GetString("adduser_notfilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string adduser_password {
            get {
                return ResourceManager.GetString("adduser_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string adduser_port {
            get {
                return ResourceManager.GetString("adduser_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn`t connect to smtp. .
        /// </summary>
        public static string adduser_smtperror {
            get {
                return ResourceManager.GetString("adduser_smtperror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UrlMailImap.
        /// </summary>
        public static string adduser_urlimap {
            get {
                return ResourceManager.GetString("adduser_urlimap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UrlMailSmtp.
        /// </summary>
        public static string adduser_urlsmtp {
            get {
                return ResourceManager.GetString("adduser_urlsmtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataBase.
        /// </summary>
        public static string db {
            get {
                return ResourceManager.GetString("db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears User list.
        /// </summary>
        public static string db_clearfolder {
            get {
                return ResourceManager.GetString("db_clearfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Mail list.
        /// </summary>
        public static string db_clearmail {
            get {
                return ResourceManager.GetString("db_clearmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Folder list.
        /// </summary>
        public static string db_clearuser {
            get {
                return ResourceManager.GetString("db_clearuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred in the application. Would you like to send a reply to the author?.
        /// </summary>
        public static string error_descr {
            get {
                return ResourceManager.GetString("error_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error_tittle {
            get {
                return ResourceManager.GetString("error_tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string feedback_send {
            get {
                return ResourceManager.GetString("feedback_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe what went wrong.
        /// </summary>
        public static string feedback_tittle {
            get {
                return ResourceManager.GetString("feedback_tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wav files.
        /// </summary>
        public static string files_wav {
            get {
                return ResourceManager.GetString("files_wav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string folder_archive {
            get {
                return ResourceManager.GetString("folder_archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string folder_draft {
            get {
                return ResourceManager.GetString("folder_draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        public static string folder_inbox {
            get {
                return ResourceManager.GetString("folder_inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spam.
        /// </summary>
        public static string folder_junk {
            get {
                return ResourceManager.GetString("folder_junk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plese select folder.
        /// </summary>
        public static string folder_select {
            get {
                return ResourceManager.GetString("folder_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash.
        /// </summary>
        public static string folder_trash {
            get {
                return ResourceManager.GetString("folder_trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string help_about {
            get {
                return ResourceManager.GetString("help_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string help_check {
            get {
                return ResourceManager.GetString("help_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendFeedback.
        /// </summary>
        public static string help_feedback {
            get {
                return ResourceManager.GetString("help_feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string help_options {
            get {
                return ResourceManager.GetString("help_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string langName {
            get {
                return ResourceManager.GetString("langName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string mail_menu_delete {
            get {
                return ResourceManager.GetString("mail_menu_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to ....
        /// </summary>
        public static string mail_menu_moveto {
            get {
                return ResourceManager.GetString("mail_menu_moveto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string mail_menu_reply {
            get {
                return ResourceManager.GetString("mail_menu_reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resent.
        /// </summary>
        public static string mail_menu_resent {
            get {
                return ResourceManager.GetString("mail_menu_resent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string message_from {
            get {
                return ResourceManager.GetString("message_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme: {0}.
        /// </summary>
        public static string message_namelist {
            get {
                return ResourceManager.GetString("message_namelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail not find..
        /// </summary>
        public static string message_notfound {
            get {
                return ResourceManager.GetString("message_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string message_send {
            get {
                return ResourceManager.GetString("message_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string message_theme {
            get {
                return ResourceManager.GetString("message_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string message_to {
            get {
                return ResourceManager.GetString("message_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write message.
        /// </summary>
        public static string message_write {
            get {
                return ResourceManager.GetString("message_write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded {0} of {1} messages.
        /// </summary>
        public static string record_mess {
            get {
                return ResourceManager.GetString("record_mess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string settings_default {
            get {
                return ResourceManager.GetString("settings_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (ms) between mail checks.
        /// </summary>
        public static string settings_mailChecks {
            get {
                return ResourceManager.GetString("settings_mailChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply &amp; Close.
        /// </summary>
        public static string settings_ok {
            get {
                return ResourceManager.GetString("settings_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Email sound.
        /// </summary>
        public static string settings_pickSound {
            get {
                return ResourceManager.GetString("settings_pickSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum time (ms) between two connections.
        /// </summary>
        public static string settings_timeConn {
            get {
                return ResourceManager.GetString("settings_timeConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        public static string user_add {
            get {
                return ResourceManager.GetString("user_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Users for Folders.
        /// </summary>
        public static string user_check {
            get {
                return ResourceManager.GetString("user_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Users &amp; Folders.
        /// </summary>
        public static string user_load {
            get {
                return ResourceManager.GetString("user_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available!.
        /// </summary>
        public static string version_available {
            get {
                return ResourceManager.GetString("version_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} available!.
        /// </summary>
        public static string version_availablem {
            get {
                return ResourceManager.GetString("version_availablem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking updates!.
        /// </summary>
        public static string version_error {
            get {
                return ResourceManager.GetString("version_error", resourceCulture);
            }
        }
    }
}
